name: CI (machine learning)

on:
  push:
    paths:
      - "machine-learning-client/**"
      - ".github/workflows/ci-ml.yml"
  pull_request:
    paths:
      - "machine-learning-client/**"
  workflow_dispatch:

jobs:
  build-and-test-ml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: machine-learning-client
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: machine-learning-client
        run: pytest

      - name: Build Docker image
        run: docker build -t ml-client ./machine-learning-client