name: CI (web app)

on:
  push:
    paths:
      - "web-app/**"
      - ".github/workflows/webapp-ci.yml"
  pull_request:
    paths:
      - "web-app/**"
  workflow_dispatch:

jobs:
  build-and-test-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: web-app
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: web-app
        run: pytest

      - name: Build Docker image
        run: docker build -t web-app ./web-app